### ISSUE TITLE
Questions on the output score

### ISSUE THREAD

**Issue by harshithdwivedi** [mahdihosseini/HVS-MaxPol#1]
I ran the demo on Matlab and the output was a negative number. 
When you mention that a greater number means the image is more blurred, do you mean the absolute value?
For instance, running it on sample images; the output for the sharp image is -21 and that for a blurred image is -24. 
Looking at the Matlab code, it seems to add a negative sign to the score at the end, is there a reason for doing this? 

https://github.com/mahdihosseini/HVS-MaxPol/blob/master/utilities/HVS_MaxPol.m#L110

Also, is there a threshold that you noticed above which the images are blurry and below which they're sharp?
Since this is an NR-IQA technique, I believe that there must be a dataset independent threshold that can classify blurred and non-blurred images. I noticed this number to be -23 for HVS-MaxPol-2 but again I got some false positives on testing it with a varying dataset of sharp and blurred images.

For example, the accuracy of this technique on my test dataset was around 83% for sharp images and 70% for non-sharp images.

**Comment by mahdihosseini** [comment]
Hi Harshit – Sorry for my delay, I am running through a lot of tasks and unfortunately am very limited with responses.

The threshold should be assigned based on the dataset you are dealing with. Generally speaking, the values of NR-FQA are stable and you can set a fixed threshold on particular application at hand.

You can change back the negative sign if you want to. This was just comply with the subjective scoring distribution.

Thanks,

Mahdi

**Comment by harshithdwivedi** [comment]
Sounds good, thanks!
